/**
 * Top Destinations Configuration
 * Pre-configured destinations organized by region (India/World) and month
 * This avoids frequent API calls to Groq for displaying featured destinations
 */

const topDestinations = {
  india: {
    january: [
      {
        name: 'Goa',
        country: 'India',
        description: 'Perfect beach destination with vibrant nightlife and Portuguese heritage. Ideal for winter sun seekers.',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to February',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Kerala',
        country: 'India',
        description: 'Backwaters, tea plantations, and serene landscapes. Experience the "God\'s Own Country".',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Rajasthan',
        country: 'India',
        description: 'Royal palaces, desert landscapes, and rich cultural heritage. The land of kings and forts.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Varanasi',
        country: 'India',
        description: 'Spiritual capital of India with ancient temples and Ganges river rituals. A mystical experience.',
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Darjeeling',
        country: 'India',
        description: 'Hill station with tea gardens, mountain views, and toy train rides. Perfect for nature lovers.',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, October to November',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    february: [
      {
        name: 'Andaman and Nicobar',
        country: 'India',
        description: 'Pristine beaches, crystal-clear waters, and world-class diving. Tropical paradise in India.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to May',
        budgetRange: 'high',
        region: 'india',
      },
      {
        name: 'Mysore',
        country: 'India',
        description: 'Royal city with magnificent palaces, silk markets, and rich cultural traditions.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Hampi',
        country: 'India',
        description: 'Ancient ruins, boulder-strewn landscapes, and architectural marvels from the Vijayanagara Empire.',
        image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Rishikesh',
        country: 'India',
        description: 'Yoga capital of the world, adventure sports, and spiritual retreats along the Ganges.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'February to May, September to November',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Udaipur',
        country: 'India',
        description: 'City of lakes with romantic palaces, boat rides, and stunning architecture. The Venice of the East.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'September to March',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    march: [
      {
        name: 'Ladakh',
        country: 'India',
        description: 'High-altitude desert with stunning landscapes, monasteries, and adventure activities.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to September',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Shimla',
        country: 'India',
        description: 'Queen of hill stations with colonial architecture, scenic views, and pleasant weather.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to June, October to November',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Mumbai',
        country: 'India',
        description: 'Bollywood capital with vibrant street food, colonial architecture, and bustling markets.',
        image: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Pondicherry',
        country: 'India',
        description: 'French colonial charm, beaches, and spiritual ashrams. A unique blend of cultures.',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Kolkata',
        country: 'India',
        description: 'Cultural capital with colonial heritage, literary history, and delicious Bengali cuisine.',
        image: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
    ],
    april: [
      {
        name: 'Manali',
        country: 'India',
        description: 'Mountain resort town with snow-capped peaks, adventure sports, and apple orchards.',
        image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to June, October to January',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Ooty',
        country: 'India',
        description: 'Hill station with tea gardens, botanical gardens, and toy train. The Queen of Nilgiris.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to November',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Munnar',
        country: 'India',
        description: 'Tea plantations, misty hills, and wildlife. A peaceful retreat in the Western Ghats.',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'September to May',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Coorg',
        country: 'India',
        description: 'Coffee plantations, waterfalls, and misty mountains. Scotland of India.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to May',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Alleppey',
        country: 'India',
        description: 'Backwater cruises, houseboats, and serene canals. Experience Kerala\'s unique waterways.',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to February',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    may: [
      {
        name: 'Spiti Valley',
        country: 'India',
        description: 'Remote high-altitude desert with ancient monasteries and breathtaking landscapes.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to October',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'McLeod Ganj',
        country: 'India',
        description: 'Tibetan culture, monasteries, and trekking trails. Home of the Dalai Lama.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to June, September to November',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Kodaikanal',
        country: 'India',
        description: 'Princess of hill stations with lakes, forests, and pleasant climate year-round.',
        image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Mount Abu',
        country: 'India',
        description: 'Only hill station in Rajasthan with Dilwara temples and Nakki Lake.',
        image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to June, September to November',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Gangtok',
        country: 'India',
        description: 'Capital of Sikkim with monasteries, mountain views, and Buddhist culture.',
        image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, October to December',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    june: [
      {
        name: 'Leh',
        country: 'India',
        description: 'High-altitude desert town with stunning landscapes, monasteries, and adventure activities.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to September',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Srinagar',
        country: 'India',
        description: 'Houseboats on Dal Lake, Mughal gardens, and stunning mountain scenery.',
        image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to October',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Kasol',
        country: 'India',
        description: 'Hippie paradise with Israeli cafes, trekking trails, and Parvati Valley views.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to June, October to November',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Tawang',
        country: 'India',
        description: 'Remote monastery town with stunning landscapes and Buddhist culture in Arunachal Pradesh.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to October',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Valley of Flowers',
        country: 'India',
        description: 'UNESCO World Heritage site with alpine meadows and rare Himalayan flowers.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to September',
        budgetRange: 'low',
        region: 'india',
      },
    ],
    july: [
      {
        name: 'Mahabalipuram',
        country: 'India',
        description: 'Ancient rock-cut temples, UNESCO World Heritage site, and beautiful beaches.',
        image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Kodaikanal',
        country: 'India',
        description: 'Princess of hill stations with lakes, forests, and pleasant climate year-round.',
        image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Lonavala',
        country: 'India',
        description: 'Hill station near Mumbai with waterfalls, caves, and scenic viewpoints.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to May',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Mahabaleshwar',
        country: 'India',
        description: 'Strawberry capital with viewpoints, waterfalls, and pleasant weather.',
        image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to June',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Coorg',
        country: 'India',
        description: 'Coffee plantations, waterfalls, and misty mountains. Scotland of India.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to May',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    august: [
      {
        name: 'Ladakh',
        country: 'India',
        description: 'High-altitude desert with stunning landscapes, monasteries, and adventure activities.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to September',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Sikkim',
        country: 'India',
        description: 'Mountain state with monasteries, trekking, and stunning Himalayan views.',
        image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, October to December',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Shillong',
        country: 'India',
        description: 'Scotland of the East with waterfalls, music scene, and pleasant climate.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to November',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Cherrapunji',
        country: 'India',
        description: 'Wettest place on Earth with living root bridges and stunning waterfalls.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to May',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Kodaikanal',
        country: 'India',
        description: 'Princess of hill stations with lakes, forests, and pleasant climate year-round.',
        image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    september: [
      {
        name: 'Rajasthan',
        country: 'India',
        description: 'Royal palaces, desert landscapes, and rich cultural heritage. The land of kings and forts.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Kerala',
        country: 'India',
        description: 'Backwaters, tea plantations, and serene landscapes. Experience the "God\'s Own Country".',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Goa',
        country: 'India',
        description: 'Perfect beach destination with vibrant nightlife and Portuguese heritage. Ideal for winter sun seekers.',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to February',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Udaipur',
        country: 'India',
        description: 'City of lakes with romantic palaces, boat rides, and stunning architecture. The Venice of the East.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'September to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Mysore',
        country: 'India',
        description: 'Royal city with magnificent palaces, silk markets, and rich cultural traditions.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
    ],
    october: [
      {
        name: 'Goa',
        country: 'India',
        description: 'Perfect beach destination with vibrant nightlife and Portuguese heritage. Ideal for winter sun seekers.',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to February',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Kerala',
        country: 'India',
        description: 'Backwaters, tea plantations, and serene landscapes. Experience the "God\'s Own Country".',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Rajasthan',
        country: 'India',
        description: 'Royal palaces, desert landscapes, and rich cultural heritage. The land of kings and forts.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Varanasi',
        country: 'India',
        description: 'Spiritual capital of India with ancient temples and Ganges river rituals. A mystical experience.',
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
      {
        name: 'Darjeeling',
        country: 'India',
        description: 'Hill station with tea gardens, mountain views, and toy train rides. Perfect for nature lovers.',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, October to November',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    november: [
      {
        name: 'Goa',
        country: 'India',
        description: 'Perfect beach destination with vibrant nightlife and Portuguese heritage. Ideal for winter sun seekers.',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to February',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Kerala',
        country: 'India',
        description: 'Backwaters, tea plantations, and serene landscapes. Experience the "God\'s Own Country".',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Rajasthan',
        country: 'India',
        description: 'Royal palaces, desert landscapes, and rich cultural heritage. The land of kings and forts.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Andaman and Nicobar',
        country: 'India',
        description: 'Pristine beaches, crystal-clear waters, and world-class diving. Tropical paradise in India.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to May',
        budgetRange: 'high',
        region: 'india',
      },
      {
        name: 'Udaipur',
        country: 'India',
        description: 'City of lakes with romantic palaces, boat rides, and stunning architecture. The Venice of the East.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'September to March',
        budgetRange: 'medium',
        region: 'india',
      },
    ],
    december: [
      {
        name: 'Goa',
        country: 'India',
        description: 'Perfect beach destination with vibrant nightlife and Portuguese heritage. Ideal for winter sun seekers.',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to February',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Kerala',
        country: 'India',
        description: 'Backwaters, tea plantations, and serene landscapes. Experience the "God\'s Own Country".',
        image: 'https://images.unsplash.com/photo-1580584126903-c17d41830450?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Rajasthan',
        country: 'India',
        description: 'Royal palaces, desert landscapes, and rich cultural heritage. The land of kings and forts.',
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'medium',
        region: 'india',
      },
      {
        name: 'Andaman and Nicobar',
        country: 'India',
        description: 'Pristine beaches, crystal-clear waters, and world-class diving. Tropical paradise in India.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to May',
        budgetRange: 'high',
        region: 'india',
      },
      {
        name: 'Varanasi',
        country: 'India',
        description: 'Spiritual capital of India with ancient temples and Ganges river rituals. A mystical experience.',
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to March',
        budgetRange: 'low',
        region: 'india',
      },
    ],
  },
  world: {
    january: [
      {
        name: 'Bali',
        country: 'Indonesia',
        description: 'Tropical paradise with stunning beaches, ancient temples, and vibrant culture.',
        image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800',
        bestTimeToVisit: 'April to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Dubai',
        country: 'UAE',
        description: 'Modern metropolis with luxury shopping, stunning architecture, and desert adventures.',
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to March',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Thailand',
        country: 'Thailand',
        description: 'Golden temples, tropical beaches, and delicious street food. The Land of Smiles.',
        image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to March',
        budgetRange: 'low',
        region: 'world',
      },
      {
        name: 'Singapore',
        country: 'Singapore',
        description: 'Futuristic city-state with diverse cuisine, stunning gardens, and world-class attractions.',
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'Year-round',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Maldives',
        country: 'Maldives',
        description: 'Overwater bungalows, crystal-clear waters, and pristine beaches. Ultimate luxury escape.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to April',
        budgetRange: 'high',
        region: 'world',
      },
    ],
    february: [
      {
        name: 'Japan',
        country: 'Japan',
        description: 'Cherry blossoms, ancient temples, and cutting-edge technology. A perfect blend of old and new.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, September to November',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'New Zealand',
        country: 'New Zealand',
        description: 'Stunning landscapes, adventure sports, and friendly locals. Middle-earth comes to life.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'December to February',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Australia',
        country: 'Australia',
        description: 'Diverse landscapes, unique wildlife, and vibrant cities. The land down under.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'September to November, March to May',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Vietnam',
        country: 'Vietnam',
        description: 'Rich history, delicious cuisine, and stunning natural beauty from north to south.',
        image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'February to April, October to December',
        budgetRange: 'low',
        region: 'world',
      },
      {
        name: 'Sri Lanka',
        country: 'Sri Lanka',
        description: 'Tea plantations, ancient ruins, and beautiful beaches. The Pearl of the Indian Ocean.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'December to March',
        budgetRange: 'low',
        region: 'world',
      },
    ],
    march: [
      {
        name: 'Italy',
        country: 'Italy',
        description: 'Historic cities, world-class cuisine, and stunning art. La dolce vita awaits.',
        image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Greece',
        country: 'Greece',
        description: 'Ancient ruins, beautiful islands, and Mediterranean cuisine. A journey through history.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Spain',
        country: 'Spain',
        description: 'Vibrant culture, stunning architecture, and delicious tapas. Experience the passion.',
        image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Portugal',
        country: 'Portugal',
        description: 'Historic cities, beautiful coastlines, and world-class wine. Discover hidden gems.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to September',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Morocco',
        country: 'Morocco',
        description: 'Exotic souks, stunning architecture, and desert adventures. A feast for the senses.',
        image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, September to November',
        budgetRange: 'low',
        region: 'world',
      },
    ],
    april: [
      {
        name: 'Japan',
        country: 'Japan',
        description: 'Cherry blossoms, ancient temples, and cutting-edge technology. A perfect blend of old and new.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, September to November',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'South Korea',
        country: 'South Korea',
        description: 'Modern cities, ancient palaces, and K-pop culture. A fascinating blend of tradition and innovation.',
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to May, September to November',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Netherlands',
        country: 'Netherlands',
        description: 'Tulip fields, windmills, and charming canals. Experience the beauty of spring.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to May, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Switzerland',
        country: 'Switzerland',
        description: 'Alpine landscapes, pristine lakes, and charming villages. A picture-perfect destination.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, December to March',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Iceland',
        country: 'Iceland',
        description: 'Northern lights, geysers, and dramatic landscapes. A land of fire and ice.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
    ],
    may: [
      {
        name: 'France',
        country: 'France',
        description: 'Romantic cities, world-class cuisine, and iconic landmarks. The art of living.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Iceland',
        country: 'Iceland',
        description: 'Northern lights, geysers, and dramatic landscapes. A land of fire and ice.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Norway',
        country: 'Norway',
        description: 'Fjords, northern lights, and stunning natural beauty. A nature lover\'s paradise.',
        image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Ireland',
        country: 'Ireland',
        description: 'Rolling green hills, historic castles, and friendly locals. The Emerald Isle.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to September',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Scotland',
        country: 'Scotland',
        description: 'Historic castles, stunning highlands, and whisky distilleries. A land of legends.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to September',
        budgetRange: 'medium',
        region: 'world',
      },
    ],
    june: [
      {
        name: 'Switzerland',
        country: 'Switzerland',
        description: 'Alpine landscapes, pristine lakes, and charming villages. A picture-perfect destination.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, December to March',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Iceland',
        country: 'Iceland',
        description: 'Northern lights, geysers, and dramatic landscapes. A land of fire and ice.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Norway',
        country: 'Norway',
        description: 'Fjords, northern lights, and stunning natural beauty. A nature lover\'s paradise.',
        image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Canada',
        country: 'Canada',
        description: 'Vast wilderness, friendly cities, and stunning natural beauty. From coast to coast.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Alaska',
        country: 'USA',
        description: 'Untamed wilderness, glaciers, and wildlife. America\'s last frontier.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August',
        budgetRange: 'high',
        region: 'world',
      },
    ],
    july: [
      {
        name: 'Switzerland',
        country: 'Switzerland',
        description: 'Alpine landscapes, pristine lakes, and charming villages. A picture-perfect destination.',
        image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, December to March',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Iceland',
        country: 'Iceland',
        description: 'Northern lights, geysers, and dramatic landscapes. A land of fire and ice.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Norway',
        country: 'Norway',
        description: 'Fjords, northern lights, and stunning natural beauty. A nature lover\'s paradise.',
        image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Italy',
        country: 'Italy',
        description: 'Historic cities, world-class cuisine, and stunning art. La dolce vita awaits.',
        image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Greece',
        country: 'Greece',
        description: 'Ancient ruins, beautiful islands, and Mediterranean cuisine. A journey through history.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
    ],
    august: [
      {
        name: 'Switzerland',
        country: 'Switzerland',
        description: 'Alpine landscapes, pristine lakes, and charming villages. A picture-perfect destination.',
        image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, December to March',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Iceland',
        country: 'Iceland',
        description: 'Northern lights, geysers, and dramatic landscapes. A land of fire and ice.',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Norway',
        country: 'Norway',
        description: 'Fjords, northern lights, and stunning natural beauty. A nature lover\'s paradise.',
        image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to March (for aurora)',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Canada',
        country: 'Canada',
        description: 'Vast wilderness, friendly cities, and stunning natural beauty. From coast to coast.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'June to August, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Scotland',
        country: 'Scotland',
        description: 'Historic castles, stunning highlands, and whisky distilleries. A land of legends.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to September',
        budgetRange: 'medium',
        region: 'world',
      },
    ],
    september: [
      {
        name: 'Italy',
        country: 'Italy',
        description: 'Historic cities, world-class cuisine, and stunning art. La dolce vita awaits.',
        image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Greece',
        country: 'Greece',
        description: 'Ancient ruins, beautiful islands, and Mediterranean cuisine. A journey through history.',
        image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Spain',
        country: 'Spain',
        description: 'Vibrant culture, stunning architecture, and delicious tapas. Experience the passion.',
        image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'May to June, September to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Japan',
        country: 'Japan',
        description: 'Cherry blossoms, ancient temples, and cutting-edge technology. A perfect blend of old and new.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, September to November',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'South Korea',
        country: 'South Korea',
        description: 'Modern cities, ancient palaces, and K-pop culture. A fascinating blend of tradition and innovation.',
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'April to May, September to November',
        budgetRange: 'medium',
        region: 'world',
      },
    ],
    october: [
      {
        name: 'Japan',
        country: 'Japan',
        description: 'Cherry blossoms, ancient temples, and cutting-edge technology. A perfect blend of old and new.',
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'March to May, September to November',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Thailand',
        country: 'Thailand',
        description: 'Golden temples, tropical beaches, and delicious street food. The Land of Smiles.',
        image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to March',
        budgetRange: 'low',
        region: 'world',
      },
      {
        name: 'Vietnam',
        country: 'Vietnam',
        description: 'Rich history, delicious cuisine, and stunning natural beauty from north to south.',
        image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'February to April, October to December',
        budgetRange: 'low',
        region: 'world',
      },
      {
        name: 'Bali',
        country: 'Indonesia',
        description: 'Tropical paradise with stunning beaches, ancient temples, and vibrant culture.',
        image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800',
        bestTimeToVisit: 'April to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Nepal',
        country: 'Nepal',
        description: 'Himalayan peaks, ancient temples, and trekking adventures. Home to Mount Everest.',
        image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'October to November, March to May',
        budgetRange: 'low',
        region: 'world',
      },
    ],
    november: [
      {
        name: 'Thailand',
        country: 'Thailand',
        description: 'Golden temples, tropical beaches, and delicious street food. The Land of Smiles.',
        image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to March',
        budgetRange: 'low',
        region: 'world',
      },
      {
        name: 'Bali',
        country: 'Indonesia',
        description: 'Tropical paradise with stunning beaches, ancient temples, and vibrant culture.',
        image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800',
        bestTimeToVisit: 'April to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Dubai',
        country: 'UAE',
        description: 'Modern metropolis with luxury shopping, stunning architecture, and desert adventures.',
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to March',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Singapore',
        country: 'Singapore',
        description: 'Futuristic city-state with diverse cuisine, stunning gardens, and world-class attractions.',
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'Year-round',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Maldives',
        country: 'Maldives',
        description: 'Overwater bungalows, crystal-clear waters, and pristine beaches. Ultimate luxury escape.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to April',
        budgetRange: 'high',
        region: 'world',
      },
    ],
    december: [
      {
        name: 'Thailand',
        country: 'Thailand',
        description: 'Golden temples, tropical beaches, and delicious street food. The Land of Smiles.',
        image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to March',
        budgetRange: 'low',
        region: 'world',
      },
      {
        name: 'Bali',
        country: 'Indonesia',
        description: 'Tropical paradise with stunning beaches, ancient temples, and vibrant culture.',
        image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800',
        bestTimeToVisit: 'April to October',
        budgetRange: 'medium',
        region: 'world',
      },
      {
        name: 'Dubai',
        country: 'UAE',
        description: 'Modern metropolis with luxury shopping, stunning architecture, and desert adventures.',
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to March',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Singapore',
        country: 'Singapore',
        description: 'Futuristic city-state with diverse cuisine, stunning gardens, and world-class attractions.',
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'Year-round',
        budgetRange: 'high',
        region: 'world',
      },
      {
        name: 'Maldives',
        country: 'Maldives',
        description: 'Overwater bungalows, crystal-clear waters, and pristine beaches. Ultimate luxury escape.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80&auto=format&fit=crop',
        bestTimeToVisit: 'November to April',
        budgetRange: 'high',
        region: 'world',
      },
    ],
  },
}

/**
 * Get month name from number (1-12)
 */
const getMonthName = (monthNumber) => {
  const months = [
    'january',
    'february',
    'march',
    'april',
    'may',
    'june',
    'july',
    'august',
    'september',
    'october',
    'november',
    'december',
  ]
  return months[monthNumber - 1] || months[0]
}

/**
 * Get current month name
 */
const getCurrentMonth = () => {
  return getMonthName(new Date().getMonth() + 1)
}

export { topDestinations, getMonthName, getCurrentMonth }
